
### CONFIGURATION
config:
  width:           47                         # Maximum width/columns of window inside terminal
  height:          7                          # Maximum height/lines of window inside terminal
  text-padding:    4                          # Padding of input for each line
  shell:           '/bin/bash --login -i'     # Shell used to execute keybinding commands, set to 'false' to execute command directly
  exec-background: 'true'                     # Execute command in background
  borderless:      'false'                    # Don't draw borders when set to 'true'

### CONSTANTS
constants:
  terminal: 'termite'
  editor:   'vim'
  browser:  'waterfox'
  bin:      '~/bin'
  config:   '~/.config'
  scripts:  '@SHORTSTROKES_ROOT/scripts'

### KEYBINDINGS
keybindings:
  ## BASE
  q:     'true'                               # quit ShortStrokes program, basically do nothing

  ## OPEN applications
  ob:    '@browser'
  oq:    'qutebrowser'
  oe:    'eidolon menu'                       # eidolon - steam games menu
  oc:    '@terminal --role "BORDERLESS-TRANSPARENT-STICKY-<MEDIUM-XSMALL>" --exec irb'  # irb - calculator

  ## OPEN web pages
  wd:    '@browser https://duckduckgo.com/'   # DuckDuckGo
  wy:    '@browser https://www.youtube.com/'  # youtube
  wrub:  '@browser https://www.youtube.com/'  # youtube

  ## EDIT (config) files
  ee:    '@scripts/run.rb edit "@config/shortstrokes/config.yml" -r "BORDERLESS-STICKY-<XLARGE-MEDIUM>" -t "@terminal" -s "@SHELL" -e "@editor"'  # ShortStrokes config (this file)
  eE:    '@scripts/run.rb edit "@SHORTSTROKES_ROOT/config.yml" -r "BORDERLESS-STICKY-<XLARGE-MEDIUM>"   -t "@terminal" -s "@SHELL" -e "@editor"'  # default ShortStrokes config
  ei3:   '@scripts/run.rb run "~/bin/i3conf" -r "<LARGE-MEDIUM>"                                        -t "@terminal" -s "@SHELL"'               # i3conf
  ev:    '@scripts/run.rb edit "~/.vimrc" -r "<LARGE-LARGE>"                                            -t "@terminal" -s "@SHELL" -e "@editor"'  # vimrc
  eb:    '@scripts/run.rb edit "~/.bashrc" -r "<LARGE-LARGE>"                                           -t "@terminal" -s "@SHELL" -e "@editor"'  # bashrc

  ## ProfileRB
  pp:    '@bin/profilerb'                     # profile
  pa:    '@bin/profilerb acer,onedisp'        # profile acer,onedisp

  ## MISC
  ue:    'eidolon update'                     # update eidolon games list
  cu:    '@bin/checkupdates_notify'           # Check package updates

