
### CONFIGURATION
config:
  width:  47                                                   # Maximum width/columns of window inside terminal
  height: 7                                                    # Maximum height/lines of window inside terminal
  text_padding: 4                                              # Padding of input for each line
  shell: '/bin/bash'                                           # Shell used to execute keybinding commands, set to 'false' to execute command directly
  exec_bg: 'true'                                              # Execute command in background

### KEYBINDINGS
keybindings:
  ## BASE
  q: 'true'                                                    # quit ShortStrokes program, basically do nothing

  ## OPEN applications
  oe: 'eidolon menu'                                           # eidolon - steam games menu
  oc: 'termite --role "BORDERLESS-TRANSPARENT-STICKY-<MEDIUM-SMALL>" --exec irb'  # irb - calculator

  ## OPEN web pages
  Od: 'waterfox https://duckduckgo.com/'                       # DuckDuckGo
  Oy: 'waterfox https://www.youtube.com/'                      # youtube

  ## EDIT (config) files
  ee: 'termite --role "BORDERLESS-STICKY-<XLARGE-MEDIUM>" --exec "vim ~/.config/shortstrokes/config.yml"'        # This file
  eE: 'termite --role "BORDERLESS-STICKY-<XLARGE-MEDIUM>" --exec "vim ~/Projects/Ruby/ShortStrokes/config.yml"'  # Default config file
  ei3: 'termite --role "<LARGE-MEDIUM>" --exec ~/bin/i3conf'   # i3conf
  ev: 'termite --role "<LARGE-LARGE>" --exec "vim ~/.vimrc"'   # vimrc
  eb: 'termite --role "<LARGE-LARGE>" --exec "vim ~/.bashrc"'  # bashrc

  ## i3profile
  pp: '~/bin/i3profile'                                        # i3profile
  ph: '~/bin/i3profile h77m-arch'                              # i3profile h77m-arch
  pa: '~/bin/i3profile acer'                                   # i3profile acer
  poa: '~/bin/i3profile acer,onedisp'                          # i3profile acer,onedisp
  pA: '~/bin/i3profile aware-desktop'                          # i3profile aware

  ## MISC
  ue: 'eidolon update'                                         # update eidolon games list

