
### CONFIGURATION
config:
  width:           47
  height:          7
  text-padding:    4
  shell:           '/bin/bash --login -i'
  exec-background: 'true'
  borderless:      'false'

### CONSTANTS
constants:
  terminal: 'termite'
  editor:   'vim'
  browser:  'waterfox'
  bin:      '~/bin'
  config:   '~/.config'
  scripts:  '@SHORTSTROKES_ROOT/scripts'
  run:      '@SHORTSTROKES_ROOT/scripts/run.rb run'
  edit:     '@SHORTSTROKES_ROOT/scripts/run.rb edit'

### KEYBINDINGS
keybindings:
  ## BASE
  q:     'true'

  ## OPEN applications
  ob:    '@browser'
  oq:    'qutebrowser'
  oe:    'eidolon menu'
  oc:    '@run irb                          -r "BORDERLESS-TRANSPARENT-STICKY-<MEDIUM-XSMALL>" -t "@terminal" -s "@SHELL"'

  ## OPEN web pages in @browser
  wd:    '@browser https://duckduckgo.com/'      # DuckDuckGo
  wy:    '@browser https://www.youtube.com/'     # youtube
  wrub:  '@browser http://rubular.com/'          # Rubular

  ## OPEN web pages in qutebrowser
  Wd:    'qutebrowser https://duckduckgo.com/'   # DuckDuckGo
  Wy:    'qutebrowser https://www.youtube.com/'  # youtube
  Wrub:  'qutebrowser http://rubular.com/'       # Rubular

  ## EDIT (config) files
  ee:    '@edit "@config/shortstrokes/config.yml"       -r "BORDERLESS-STICKY-<XLARGE-MEDIUM>" -t "@terminal" -s "@SHELL" -e "@editor"'  # ShortStrokes config (this file)
  eE:    '@edit "@SHORTSTROKES_ROOT/config.yml"         -r "BORDERLESS-STICKY-<XLARGE-MEDIUM>" -t "@terminal" -s "@SHELL" -e "@editor"'  # default ShortStrokes config
  ev:    '@edit "~/.vimrc"                                       -r "BORDERLESS-<LARGE-LARGE>" -t "@terminal" -s "@SHELL" -e "@editor"'  # vimrc
  eb:    '@edit "~/.bashrc"                                      -r "BORDERLESS-<LARGE-LARGE>" -t "@terminal" -s "@SHELL" -e "@editor"'  # bashrc
  ei3:   '@run  "@bin/i3conf"                                    -r "BORDERLESS-<LARGE-LARGE>" -t "@terminal" -s "@SHELL"'               # i3conf
  ep:    '@edit "@config/profilerb/config.yml"          -r "BORDERLESS-STICKY-<XLARGE-MEDIUM>" -t "@terminal" -s "@SHELL" -e "@editor"'  # ProfileRB config

  ## ProfileRB
  pp:    '@bin/profilerb'                        # profile
  pa:    '@bin/profilerb acer,onedisp'           # profile acer,onedisp
  ## ProfileRB in new terminal
  PP:    '@run "@bin/profilerb; read -n1"              -r "BORDERLESS-STICKY-<MEDIUM-XXSMALL>" -t "@terminal" -s "@SHELL"'  # profile
  PA:    '@run "@bin/profilerb acer,onedisp; read -n1" -r "BORDERLESS-STICKY-<MEDIUM-XXSMALL>" -t "@terminal" -s "@SHELL"'  # profile acer,onedisp

  ## MISC
  ue:    'eidolon update'                        # update eidolon games list
  cu:    '@bin/checkupdates_notify'              # Check package updates
  ck:    '@bin/kdeconnect-status'                # Check kdeconnect connected devices

