#!/bin/bash

# `stow`s all directories / packages in this directory.
# All arguments are passed to the underlying `stow` command.
# Ignored packages (see `$IGNORED_PKGS` variable):
#   - `./_*`
#   - This script's filename
#   - The files README.md and LICENSE
#   - Filenames starting with `.`
# Ignored files in packages:
#   - Filenames starting with `_`
#   - Filenames ending with `.log`
#   - Filenames ending with `cmd_stdout`
#   - Filenames ending with `cmd_stderr`
#   - Filenames ending with `run_stdout`
#   - Filenames ending with `run_stderr`

set -eo pipefail

# shellcheck source=./util.sh disable=SC2155
function _dl_util_sh {
    local UTIL_VERSION="v2.2.6"
    local dir="$( dirname "$1" )/bin/bin"
    [ -f "${dir}/util.sh" ] || bash "${dir}/download-util.sh" "$UTIL_VERSION" || exit 1
    source "${dir}/util.sh"
}; _dl_util_sh "$0"

DOTS_BACKUP_SUFFIX=".pre-stow"
STOW_TARGET="$HOME"
IGNORED_PKGS=( \
    "_.\+"               \
    "$( basename "$0" )" \
    "README.md"          \
    "LICENSE"            \
)
STOW_STDERR_FILE="${ROOT}/.stow-err"

function main {
    run_stow "$@"
}

function run_stow {
    local invert_pkgs_regex
    local files

    invert_pkgs_regex="$( \
        join_by '|' "${IGNORED_PKGS[@]}" \
        | sed 's/|/\\|/g' \
    )"

    # shellcheck disable=2010
    mapfile -t files < <( \
        ls -1d -- * | grep -v '^\('"${invert_pkgs_regex}"'\)$' )

    stow_files "${files[@]}"
}

function stow_files {
    local files=("$@")

    msg "Packages to stow:"
    printf "  %s\n" "${files[@]}"

    if ! prompt_question "Stow these packages?" "n"; then
        prompt_question "Select packages to stow?" "n" || quit
        select_packages_to_stow files
        stow_files "${files[@]}"
        return
    fi

    msg "Stowing packages:"
    printf "  %s\n" "${files[@]}"

    stow \
        --target "$STOW_TARGET" \
        --ignore '^(_.*)|(.*\.log)|((cmd|run)_(stdout|stderr))$' \
        --no-folding \
        "$@" \
        "${files[@]}" \
        2> "$STOW_STDERR_FILE" \
        || maybe_backup_conflicting_dots "${files[@]}"

    ( 1>&2 cat "$STOW_STDERR_FILE" )
}

function maybe_backup_conflicting_dots {
    local conflicting_dots
    local cmd

    ( 1>&2 cat "$STOW_STDERR_FILE" )

    msg "\`stow\` didn't exit successfully. Possibly conflicting dotfiles exist."

    mapfile -t conflicting_dots < <( \
        grep -oE 'cannot stow [^[:space:]]+' "$STOW_STDERR_FILE" \
            | rev | cut -d" " -f1 | rev \
            | sort | uniq \
            | sed 's,^\w\+\?/\w\+\?/\(.\+$\),'"${STOW_TARGET}"'/\1,'
    )

    [ ${#conflicting_dots[@]} -gt 0 ] \
        || {
            warn "No conflicing dots? Exiting"
            exit 1
        }

    msg "Conflicting files:"
    printf "  %s\n" "${conflicting_dots[@]}"

    prompt_question "Automatically rename all conflicting dotfiles with the suffix \`${DOTS_BACKUP_SUFFIX}\`?" "n" \
        || quit
    msg "Renaming conflicting dotfiles with suffix \`${DOTS_BACKUP_SUFFIX}\`..."

    for dotfile in "${conflicting_dots[@]}"; do
        try_run mv "$dotfile" "${dotfile}${DOTS_BACKUP_SUFFIX}"
    done

    msg "Moved all files, running \`stow\` again..."
    stow_files "$@"
}

function select_packages_to_stow {
    local -n return_files="$1"

    msg "Enter space-separated list of package names to stow:"

    local selected_files=()
    read -ra selected_files

    return_files=()
    for file in "${selected_files[@]}"; do
        [ -d "$file" ] || {
            warn "Package \`${file}\` not found, skipping"
            continue
        }
        return_files+=( "$file" )
    done
}

function quit {
    echo "Exiting"
    exit 1
}

function cleanup {
    code=$?
    [ -f "$STOW_STDERR_FILE" ] && rm "$STOW_STDERR_FILE"
    return $code
}

trap cleanup EXIT QUIT TERM INT

main "$@"
