unstable_features = true

# Stable
combine_control_expr = false
max_width = 80

# Unstable
comment_width                = 80
enum_discrim_align_threshold = 40
format_strings               = true
format_macro_matchers        = true
imports_layout               = "HorizontalVertical"
struct_field_align_threshold = 40
spaces_around_ranges         = true
empty_item_single_line       = false
