#!/bin/bash
export color="$color_music"
export max_length="$music_max_length"
export truncate_char="$music_truncate_char"
export truncate_char_size="$music_truncate_char_size"

script="${HOME}/.cargo/bin/cmus-status-line"

[ -f "$script" ] \
    && "$script" 2> /dev/null
