#!/bin/bash

limit_percent=80
prefix=' '
color="$color_primary"
output=

DF_TOTAL=
DF_USED=
DF_AVAIL=
DF_PERC=

df_cols=()
mapfile -t df_cols < <( \
    df -h "$HOME" \
    | tail -n-1 \
    | tr -s ' ' $'\n'
)

DF_TOTAL="${df_cols[1]}"
DF_USED="${df_cols[2]}"
DF_AVAIL="${df_cols[3]}"
DF_PERC="${df_cols[4]}"

[ ${DF_PERC%\%} -ge $limit_percent ] \
    && color="#FF0000"

if [ -n "$BLOCK_BUTTON" ]; then
    output="${DF_USED}/${DF_TOTAL} (${DF_PERC})"
else
    output="${DF_USED}/${DF_TOTAL}"
fi

echo -e "${prefix}${output}\n\n${color}"
