#!/bin/bash

export LC_NUMERIC="en_US.UTF-8"

prefix=' '
free_output="$( free -h | cut -d$'\n' -f2 )"
# free_avail="$( echo -n "$free_output" | tr -s ' ' | cut -d' ' -f7 )"
free_used="$( echo -n "$free_output" | tr -s ' ' | cut -d' ' -f3 )"
free_total="$( echo -n "$free_output" | tr -s ' ' | cut -d' ' -f2 )"
output=

if [ -n "$BLOCK_BUTTON" ]; then
    perc="$(  echo "${free_used%%[A-z]*} / ${free_total%%[A-z]*} * 100" \
        | bc -l \
        | cut -d'.' -f1 \
    )"
    output="${free_used}/${free_total} (${perc}%)"
else
    output="${free_used}/${free_total}"
fi
echo "${prefix}${output}"
