#!/bin/bash
prefix=  #' '
suffix=
color="$color_music"
max_size="$music_max_length"
truncate_char="$music_truncate_char"
truncate_char_size="$music_truncate_char_size"
title="$( ps aux | grep -v grep | grep -Po '.*mpv.*http.*' | awk -F'title' '{print $2}' | awk -F' --' '{print $1}' | sed 's/^ //' | tr -d '\n' )"
if [ -n "$title" ]; then
	title_size="${#title}"
	final="${title}"
	if [ $title_size -gt $max_size ]; then
		size=$(( $max_size - $truncate_char_size ))
		dots=''
		for (( count = 0; count < $truncate_char_size; count++ )); do
			dots="${dots}${truncate_char}"
		done
		final="${title:0:${size}}${dots}"
	fi
	final="$( echo "$final" | sed 's/&/&amp;/g' | sed 's/</&lt;/g' | sed 's/>/&gt;/g' )"
	echo -e "<small>${prefix}${final}${suffix}</small>\n"
	echo "${color}"
fi
