#!/bin/bash

set -e

command -v vnstat &> /dev/null \
    || exit 1

interface="$( ifget )"
prefix=' '

stats=()
mapfile -t stats < <( \
    vnstat -i "$interface" --oneline \
    | tr -s ';' $'\n' \
)

# 0.  version
# 1.  interface
# 2.  timestamp today
# 3.  rx today
# 4.  tx today
# 5.  total today
# 6.  avg traffic today
# 7.  timestamp month
# 8.  rx month
# 9.  tx month
# 10. total month
# 11. avg traffic month
# 12. rx alltime
# 13. tx alltime
# 14. total alltime
# echo "${stats[3]}"

output=
suffix="<span color='${color_secondary}' size='smaller'>(${interface})</span>"

if [ -n "$BLOCK_BUTTON" ]; then
    output="${stats[8]}(month)" # rx month
else
    output="${stats[3]}" # rx today
fi

echo "${prefix}${output}${suffix}"
