#!/bin/bash
#PROFILE = h77m-arch
##interface='enp2s0'
#PROFILE = aware-desktop
interface='enp0s31f6'
#PROFILE = acer
##interface='wlp2s0'
prefix=' '
interface_color="$color_secondary"
vnstat_output="$( vnstat -i $interface --oneline | tr -d ' ' )"
vnstat_rx_today="$( echo -n "$vnstat_output" | cut -d';' -f4 )"
vnstat_rx_month="$( echo -n "$vnstat_output" | cut -d';' -f9 )"
final="${vnstat_rx_today}/${vnstat_rx_month}<span color='$interface_color' size='smaller'>(${interface})</span>"
echo "${prefix}${final}"
