---
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:tab-bar"
    - direction: Vertical
      body: true
    # - direction: Vertical
    #   borderless: true
    #   split_size:
    #     Fixed: 2
    #   run:
    #     plugin:
    #       location: "zellij:status-bar"

tabs:
  - name: "dev"
    direction: Horizontal
    focus: true
    parts:
      - direction: Vertical
        focus: true
        # run:
        #   command:
        #     cmd: nvim
      - direction: Vertical
        split_size:
          Percent: 25
        parts:
          - direction: Vertical
          - direction: Vertical
  - name: "fs"
    direction: Horizontal
    run:
      command:
        cmd: ranger
