#!/bin/bash
#PROFILE_START = h77m-arch
interface='enp2s0'
prefix=' '
#PROFILE_END
ping_limit_ms=100.0
color="$color"
ip_addr="$( ip a show $interface | grep -Eo 'inet ([0-9][0-9]?[0-9]?(\.|\/)){4}' | tr -d '/' | cut -d' ' -f2 )"
final="${prefix}${ip_addr}"
if [ -z "$final" ]; then
	color='#FF0000'
	final="No IP ($interface)"
fi
ping_ip='1.0.0.1'
ping_output="$( ping -c 1 -q $ping_ip )"
ping_avg="$( echo -n "$ping_output" | grep -E 'rtt min/avg/max/mdev =' | cut -d' ' -f4 | cut -d'/' -f2 )"
if [ -n "$ping_avg" ]; then
	if [[ "$( echo "$ping_avg >= $ping_limit_ms" | bc )" == "1" ]]; then
		color='#AAAA00'
	fi
	final="${final} (${ping_avg}ms)"
fi
echo -e "${final}\n"
echo "$color"
