#!/bin/bash
prefix=' '
free_output="$( free -h | cut -d$'\n' -f2 )"
free_avail="$( echo -n "$free_output" | tr -s ' ' | cut -d' ' -f7 )"
free_used="$( echo -n "$free_output" | tr -s ' ' | cut -d' ' -f3 )"
free_total="$( echo -n "$free_output" | tr -s ' ' | cut -d' ' -f2 )"
if [ -n "$BLOCK_BUTTON" ]; then
	final="${free_used}/${free_total}"
else
	final="${free_avail}"
fi
echo "${prefix}${final}"
