#!/bin/bash
prefix=
prefix_off=''
prefix_low=''
prefix_med=''
prefix_hig=''
suffix='%'
color="$color"
device='Master'
case "$BLOCK_BUTTON" in
	'1'|'2'|'3')
		$HOME/bin/chvol -q togglemute
		;;
	'4')
		$HOME/bin/chvol -q incr 5
		;;
	'5')
		$HOME/bin/chvol -q decr 5
		;;
esac
vol="$( amixer get $device | grep -Eo '[0-9][0-9]?[0-9]?%' | sed 's/%//' | cut -d$'\n' -f1 )"
is_off="$( amixer get $device | grep -Eo '\[off\]' )"
if   [[ $vol -eq 0  || -n "$is_off" ]]; then  # MUTE
	prefix="$prefix_off"
	color="#884400"
elif [[ $vol -gt 0  && $vol -lt 25 ]]; then   # LOW
	prefix="$prefix_low"
elif [[ $vol -ge 25 && $vol -lt 75 ]]; then   # MEDIUM
	prefix="$prefix_med"
elif [[ $vol -ge 75 && $vol -lt 100 ]]; then  # HIGH
	prefix="$prefix_hig"
	color="#FF8800"
fi
echo -e "${prefix} ${vol}${suffix}\n"
echo $color
