## Settings
# Show image previews
set preview_images true
# Edit file
#copymap E e

## Keymaps
# Execute file
map e execute_command ./%f

# Bulk rename selected files
map R bulkrename %s

# Force quit ranger
map Q quitall!

# Start shell in current directory (disable cdpath)
map S shell sh -c "AUTO_CDPATH=0 exec ${SHELL}"
