### CONFIGURATION
config:
  width:           47
  height:          7
  text-padding:    4
  shell:           '/bin/bash --login'
  exec-background: 'true'
  borderless:      'false'
  cmd-stdout:      '@SHORTSTROKES_ROOT/.out/cmd_stdout'
  cmd-stderr:      '@SHORTSTROKES_ROOT/.out/cmd_stderr'

### CONSTANTS
constants:
  terminal:   'alacritty'
  editor:     'nvim'
  browser:    'firefox'
  config:     '~/.config'
  conf:       '~/conf'
  scripts:    '@SHORTSTROKES_ROOT/scripts'
  i3scripts:  '~/.config/i3/scripts'
  #PROFILE_START = !aware-desktop && !desktop-manjaro && !h77m-arch
  ##run:        '@SHORTSTROKES_ROOT/scripts/run.rb run'
  ##edit:       '@SHORTSTROKES_ROOT/scripts/run.rb edit'
  #PROFILE_END
  #PROFILE_START = aware-desktop || desktop-manjaro || h77m-arch
  run:        '~/bin/runrb run'
  edit:       '~/bin/runrb edit'
  #PROFILE_END
  SSROOT:     '@SHORTSTROKES_ROOT'
  projects:   '~/Projects'
  ruby:       '~/Projects/Ruby'
  bash:       'bash --login'
  eidolon:    '~/.cargo/bin/eidolon'

### KEYBINDINGS
keybindings:
  ## BASE
  q:     'true'

  ## Start Terminal
  tb:    '@terminal -e "@bash"'
  Tb:    '@terminal -e "@bash" -r "FLOAT-TRANSPARENT"'

  ## Open applications
  ob:    '@browser'
  oq:    'qutebrowser'
  ww:    '@browser'
  WW:    'qutebrowser'
  oe:    '@eidolon menu'
  oc:    '@run irb                                                 -r "BORDERPIXEL-TRANSPARENT-STICKY-<MEDIUM-XSMALL>" -t "@terminal" -s "@SHELL"'  # irb (calculator)
  ov:    '@run virb                                                  -r "BORDERPIXEL-TRANSPARENT-STICKY-<LARGE-SMALL>" -t "@terminal" -s "@SHELL"'  # virb
  'on':  '@run "ncpamixer"                                           -r "BORDERPIXEL-TRANSPARENT-STICKY-<LARGE-SMALL>" -t "@terminal" -s "@SHELL"'  # NOTE: 'on' without quotation marks is considered a truthy value in YAML, and will therefor be parsed as true
  # ol:    'feh -x --force-aliasing --zoom fill ~/Screenshots/by_date/latest'                                                                        # Open latest screenshot (feh)
  ol:    'sxiv ~/Pictures/Screenshots/by_date/latest'                                                                                              # Open latest screenshot (sxiv)
  cal:   '@run "if which calcu &> /dev/null; then calcu; else calcurse; fi" -r "BORDERPIXEL-TRANSPARENT-<LARGE-SMALL>" -t "@terminal" -s "@SHELL"'  # Open calcurse (with calcu script, if available)

  ## Open web pages in @browser
  wd:    '@browser https://duckduckgo.com/'      # DuckDuckGo
  wy:    '@browser https://www.youtube.com/'     # youtube
  wrub:  '@browser http://rubular.com/'          # Rubular

  ## Open web pages in qutebrowser
  Wd:    'qutebrowser https://duckduckgo.com/'   # DuckDuckGo
  Wy:    'qutebrowser https://www.youtube.com/'  # youtube
  Wrub:  'qutebrowser http://rubular.com/'       # Rubular

  ## Edit (config) files
  ee:    '@edit "@config/shortstrokes/config.yml"            -r "BORDERPIXEL-STICKY-<XXLARGE-MEDIUM>" -t "@terminal" -s "@SHELL" -e "@editor"'  # ShortStrokes config (this file)
  eE:    '@edit "@SSROOT/config.yml"                          -r "BORDERPIXEL-STICKY-<XLARGE-MEDIUM>" -t "@terminal" -s "@SHELL" -e "@editor"'  # default ShortStrokes config
  ev:    '@edit "~/.vimrc"                                             -r "BORDERPIXEL-<LARGE-LARGE>" -t "@terminal" -s "@SHELL" -e "@editor"'  # vimrc - floating
  Ev:    '@edit "~/.vimrc"                                                                           -t "@terminal" -s "@SHELL" -e "@editor"'  # vimrc
  eb:    '@edit "~/.bashrc"                                            -r "BORDERPIXEL-<LARGE-LARGE>" -t "@terminal" -s "@SHELL" -e "@editor"'  # bashrc - floating
  Eb:    '@edit "~/.bashrc"                                                                          -t "@terminal" -s "@SHELL" -e "@editor"'  # bashrc
  ez:    '@edit "~/.zshrc"                                             -r "BORDERPIXEL-<LARGE-LARGE>" -t "@terminal" -s "@SHELL" -e "@editor"'  # zshrc - floating
  Ez:    '@edit "~/.zshrc"                                                                           -t "@terminal" -s "@SHELL" -e "@editor"'  # zshrc
  ei3:   '@run  "i3conf"                                               -r "BORDERPIXEL-<LARGE-LARGE>" -t "@terminal" -s "@SHELL"'               # i3conf - floating
  Ei3:   '@run  "i3conf"                                                                             -t "@terminal" -s "@SHELL"'               # i3conf
  ep:    '@edit "@config/profilerb/config.yml"                -r "BORDERPIXEL-STICKY-<XLARGE-MEDIUM>" -t "@terminal" -s "@SHELL" -e "@editor"'  # ProfileRB config
  eP:    '@edit "@ruby/ProfileRB/config.yml"                  -r "BORDERPIXEL-STICKY-<XLARGE-MEDIUM>" -t "@terminal" -s "@SHELL" -e "@editor"'  # ProfileRB default config
  ec:    '@edit "@config/compton.conf"            -r "BORDERPIXEL-STICKY-TRANSPARENT-<XLARGE-MEDIUM>" -t "@terminal" -s "@SHELL" -e "@editor"'  # compton config - floating
  Ec:    '@edit "@config/compton.conf"                                                               -t "@terminal" -s "@SHELL" -e "@editor"'  # compton config
  eq:    '@edit "@config/qutebrowser/config.py"                      -r "BORDERPIXEL-<XLARGE-MEDIUM>" -t "@terminal" -s "@SHELL" -e "@editor"'  # qutebrowser config - floating
  Eq:    '@edit "@config/qutebrowser/config.py"                                                      -t "@terminal" -s "@SHELL" -e "@editor"'  # qutebrowser config
  en:    '@edit "~/misc/notes"                                 -r "BORDERPIXEL-STICKY-<LARGE-MEDIUM>" -t "@terminal" -s "@SHELL" -e "@editor"'  # ~/misc/notes
  ew:    '@run "@editor +VimwikiIndex"                         -r "BORDERPIXEL-STICKY-<LARGE-MEDIUM>" -t "@terminal" -s "@SHELL"'               # vimwiki

  ## Floating terminal with ranger
  rr:    '@run "ranger ~"                                       -r "FLOAT-BORDERPIXEL-<LARGE-MEDIUM>" -t "@terminal" -s "@SHELL"'  # home
  rh:    '@run "ranger ~"                                       -r "FLOAT-BORDERPIXEL-<LARGE-MEDIUM>" -t "@terminal" -s "@SHELL"'  # home
  r/:    '@run "ranger /"                                       -r "FLOAT-BORDERPIXEL-<LARGE-MEDIUM>" -t "@terminal" -s "@SHELL"'  # root
  rm:    '@run "ranger ~/misc"                                  -r "FLOAT-BORDERPIXEL-<LARGE-MEDIUM>" -t "@terminal" -s "@SHELL"'  # misc
  rd:    '@run "ranger ~/Downloads"                             -r "FLOAT-BORDERPIXEL-<LARGE-MEDIUM>" -t "@terminal" -s "@SHELL"'  # downloads
  rP:    '@run "ranger ~/Projects"                              -r "FLOAT-BORDERPIXEL-<LARGE-MEDIUM>" -t "@terminal" -s "@SHELL"'  # projects
  rp:    '@run "ranger ~/Pictures"                              -r "FLOAT-BORDERPIXEL-<LARGE-MEDIUM>" -t "@terminal" -s "@SHELL"'  # pictures
  rs:    '@run "ranger ~/Pictures/Screenshots"                  -r "FLOAT-BORDERPIXEL-<LARGE-MEDIUM>" -t "@terminal" -s "@SHELL"'  # screenshots
  rv:    '@run "ranger ~/Videos"                                -r "FLOAT-BORDERPIXEL-<LARGE-MEDIUM>" -t "@terminal" -s "@SHELL"'  # videos
  rc:    '@run "ranger @config"                                 -r "FLOAT-BORDERPIXEL-<LARGE-MEDIUM>" -t "@terminal" -s "@SHELL"'  # config
  rC:    '@run "ranger @conf"                                   -r "FLOAT-BORDERPIXEL-<LARGE-MEDIUM>" -t "@terminal" -s "@SHELL"'  # conf (repo)
  ri3:   '@run "ranger @config/i3"                              -r "FLOAT-BORDERPIXEL-<LARGE-MEDIUM>" -t "@terminal" -s "@SHELL"'  # config - i3
  rz:    '@run "ranger @config/zsh-custom"                      -r "FLOAT-BORDERPIXEL-<LARGE-MEDIUM>" -t "@terminal" -s "@SHELL"'  # config - zsh

  ## ProfileRB
  pp:    'profilerb'                                                                                                              # profile
  pa:    'profilerb acer,onedisp'                                                                                                 # profile acer,onedisp
  ## ProfileRB in new terminal
  PP:    '@run "profilerb | less"                             -r "BORDERPIXEL-STICKY-<MEDIUM-XSMALL>" -t "@terminal" -s "@SHELL"'  # profile
  PA:    '@run "profilerb acer,onedisp | less"                -r "BORDERPIXEL-STICKY-<MEDIUM-XSMALL>" -t "@terminal" -s "@SHELL"'  # profile acer,onedisp

  ## MISC
  ue:    '@eidolon update'                       # update eidolon games list
  cu:    'checkupdates_notify'                   # Check package updates
  ck:    'kdeconnect-status'                     # Check kdeconnect connected devices
  # Get xprop, start xprop with cursor selection
  gx:    '@run "xprop | less"                                  -r "BORDERPIXEL-STICKY-<LARGE-MEDIUM>" -t "@terminal" -s "@SHELL"'
  # CMUS search for track
  cs:    '@run @i3scripts/cmus-search.sh          -r "BORDERPIXEL-TRANSPARENT-STICKY-<SMALL-XXSMALL>" -t "@terminal" -s "@SHELL"'
  # Rerverse clipboard content
  mr:    '@scripts/reverse.rb'
  # Randomize clipboard content letter cases
  mc:    '@scripts/case.rb'
  # Put date with format '%Y-%m-%d' into clipboard
  md:    "date +'%Y-%m-%d' | xclip -i -selection clipboard"
  # Start vitetris
  vt:    '@run vitetris                                              -r "<MEDIUM-MEDIUM>-BORDERPIXEL" -t "@terminal" -s "bash"'
  # Toggle US and DE keyboard layouts
  kk:    '~/bin/toggle-layout-us-de'
  # Pickers: color, emoji
  pc:    'xcolor -s clipboard'
  pe:    'emojipicker'
