#!/bin/bash
prefix=''
color="$color_primary"
color_crt="#FF0000"
color_low="#FFAA00"
color_ful="#00CC00"
color_chr="#AAAA00"
sym_bat_0=' '  #  0 ...  13
sym_bat_1=' '  # 13 ...  38
sym_bat_2=' '  # 38 ...  63
sym_bat_3=' '  # 63 ...  88
sym_bat_4=' '  # 88 ..  100
sym_chr=' '
acpi_output="$( acpi -b )"
percent="$( echo -n "$acpi_output" | grep -Eo '[0-9][0-9]?[0-9]?%' )"
percent_int="$( echo -n "$percent" | tr -d '%' )"
state="$( echo -n "$acpi_output" | grep -Eo ': \w+' | tr -d ': ' )"
case "$state" in
	'Charging')
		prefix="${prefix}${sym_chr}"
		color="$color_chr"
		;;
	'Discharging')
		if   [[                        $percent_int -lt 13 ]]; then
			prefix="${prefix}${sym_bat_0}"
			color="$color_crt"
		elif [[ $percent_int -ge 13 && $percent_int -lt 38 ]]; then
			prefix="${prefix}${sym_bat_1}"
			color="$color_low"
		elif [[ $percent_int -ge 38 && $percent_int -lt 63 ]]; then
			prefix="${prefix}${sym_bat_2}"
		elif [[ $percent_int -ge 63 && $percent_int -lt 88 ]]; then
			prefix="${prefix}${sym_bat_3}"
		elif [[ $percent_int -ge 88                        ]]; then
			prefix="${prefix}${sym_bat_4}"
			color="$color_ful"
		fi
		;;
	*)
		prefix="${prefix}${sym_bat_2}"
		;;
esac
final="${prefix}${percent}"
echo -e "${final}\n"
echo "$color"
