#!/bin/bash
display_type="$BLOCK_INSTANCE"  # Either 'available' or 'percent'
limit_percent=80
dev_one='/home'
dev_two='/'
prefix=' '
color="$color_primary"
df_column_avail=4
df_column_use_percent=5
output="$( df -h $dev_one $dev_two | tr -s ' ' | cut -d' ' -f$df_column_avail,$df_column_use_percent | cut -d$'\n' -f2,3 )"
avail_one="$( echo -n "$output" | cut -d$'\n' -f1 | cut -d' ' -f1 )"
avail_two="$( echo -n "$output" | cut -d$'\n' -f2 | cut -d' ' -f1 )"
use_one="$( echo -n "$output" | cut -d$'\n' -f1 | cut -d' ' -f2 )"
use_two="$( echo -n "$output" | cut -d$'\n' -f2 | cut -d' ' -f2 )"
use_int_one="$( echo -n "$use_one" | sed 's/%//' )"
use_int_two="$( echo -n "$use_two" | sed 's/%//' )"
if [[ $use_int_one -ge $limit_percent || $use_int_two -ge $limit_percent ]]; then
	color="#FF0000"
fi
if [ -n "$BLOCK_BUTTON" ]; then
	if   [ "$display_type" == 'available' ]; then
		display_type='percent'
	elif [ "$display_type" == 'percent' ]; then
		display_type='available'
	fi
fi
if   [ "$display_type" == 'available' ]; then
	final="${avail_one}/${avail_two}"
elif [ "$display_type" == 'percent' ]; then
	final="${use_one}/${use_two}"
else
	final="${use_one}/${use_two}"
fi
final="${prefix}${final}"
echo -e "$final\n"
echo "$color"