format = """
<span size="small" color="#44AAAA">
%{ If(
    Or(IsStatus(Playing), IsStatus(Paused)),
    Container([
        Container([
            Text("<span color='#44AA44'>"),
            If(IsStatus(Playing),
                Text(" ")),
            If(IsStatus(Paused),
                Text(" ")),
            If(IsStatus(Stopped),
                Text(" ")),
            Text("</span>"),
        ]),

        If(
            IsStatus(Playing),
            Container([
                HtmlEscape(Truncate(Title, 60)),
                Text(" <span color='#44AA44' size='smaller'></span> "),
                Container([
                    Text("<span color='#AA8844'>"),
                    HtmlEscape(ProgressBar("◄▬▬▬▬————►")),
                    Text("</span>"),
                ]),
            ]),
        ),

        If(
            IsStatus(Paused),
            Container([
                Text("<span size='smaller'>"),
                HtmlEscape(Truncate(Title, 10)),
                Text(" "),
                HtmlEscape(ProgressBar("◄▬▬—►")),
                Text("</span>"),
            ]),
        ),
    ]),
)}
</span>
"""
