format = """
<span size="small" color="teal">
%{ If(
    Or(IsStatus(Playing), IsStatus(Paused)),
    HtmlEscape(
        Container([
            Container([
                If(IsStatus(Playing),
                    Text(" ")),
                If(IsStatus(Paused),
                    Text(" ")),
                If(IsStatus(Stopped),
                    Text(" ")),
            ]),

            If(
                IsStatus(Playing),
                Container([
                    Truncate(Title, 60),
                    Text("  "),
                    ProgressBar("<####---->"),
                ]),
            ),

            If(
                IsStatus(Paused),
                Container([
                    Truncate(Title, 10),
                    Text(" "),
                    ProgressBar("<##->"),
                ]),
            ),
        ]),
    ),
)}
</span>
"""
